set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

run-shell ~/clone/path/resurrect.tmux

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#1F1F28 fg=#7E9CD8' # rose-pine
#set -g status-style 'fg=#CCFDBF bg=#4F4944' # gray-white
#set -g status-style 'fg=#EAEEAE bg=#0B0B0B' # kamogawa (is that how you spell it?)
#set -g status-style 'fg=#f22f11 bg=#2C2722' # red (for some reason)


bind r source-file ~/.tmux.conf
set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim motioning pane switching (dont really use panes)
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
#                                               PRIMEAGEN MENTION, lets go
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
bind-key -r W run-shell "~/.local/bin/tmux-sessionizer ~/work/"
bind-key -r E run-shell "~/.local/bin/tmux-sessionizer ~/work/elit"
bind-key -r C run-shell "~/.local/bin/tmux-sessionizer ~/work/vfp-lsp"
