#!/usr/bin/env bash

sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git ~/paru
pushd ~/paru
makepkg -si
popd

paru -S just --noconfirm
paru -S --noconfirm --needed gimp tldr go rust fzf btop bc stylua bun neovim ripgrep ghostty
paro -S --noconfirm --needed claude-code opencode-bin tmux
paru -S --noconfirm cursor-bin cursor-cli
paru -S --noconfirm nodejs npm
paru -S love --noconfirm --needed
paru -S ttf-font-awesome waybar ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols --noconfirm
paru -S ghostty --noconfirm
paru -Syu wlogout-git --noconfirm --needed

# cloudflare stuff
paru -S cloudflared --noconfirm
paru -S dosfstools --noconfirm
paru -S arp-scan avahi nss-mdns --noconfirm
